### DISCUSSION TITLE
Listen to Alternate MQTT Topic

### DISCUSSION THREAD

**Discussion by broswell** [helgeerbe/picframe#211] [Q&A] [answered]
I have an inexpensive remote control that talks of 433MHZ.  Pushing the button (using rtl_433) generates the following in MQTT:
rtl_433/alarm/events {"time":"2022-01-04 17:29:24","model":"Generic Remote","id":57173,"cmd":48,"tristate":"1Z11ZZZZ0100"}
rtl_433/alarm/devices/Generic_Remote/57173/time 2022-01-04 17:29:24
rtl_433/alarm/devices/Generic_Remote/57173/id 57173
rtl_433/alarm/devices/Generic_Remote/57173/cmd 48
rtl_433/alarm/devices/Generic_Remote/57173/tristate 1Z11ZZZZ0100
rtl_433/alarm/events {"time":"2022-01-04 17:29:24","model":"Generic Remote","id":57173,"cmd":48,"tristate":"1Z11ZZZZ0100"}
rtl_433/alarm/devices/Generic_Remote/57173/time 2022-01-04 17:29:24
rtl_433/alarm/devices/Generic_Remote/57173/id 57173
rtl_433/alarm/devices/Generic_Remote/57173/cmd 48
rtl_433/alarm/devices/Generic_Remote/57173/tristate 1Z11ZZZZ0100
rtl_433/alarm/events {"time":"2022-01-04 17:29:24","model":"Generic Remote","id":57173,"cmd":48,"tristate":"1Z11ZZZZ0100"}
rtl_433/alarm/devices/Generic_Remote/57173/time 2022-01-04 17:29:24
rtl_433/alarm/devices/Generic_Remote/57173/id 57173
rtl_433/alarm/devices/Generic_Remote/57173/cmd 48

What is the best way to make the slide advance on the message ?
rtl_433/alarm/devices/Generic_Remote/57173/cmd 48 and debounce the output (sometimes 2x, sometimes 3x)

1) Modify the code
2 Write a demon to listen and then send the correct command 
 mosquitto_pub -h localhost -t homeassistant/switch/picframe_next/set -m "ON"
3) Use Home assistant to listen and then send the mqtt commands?

Thanks for writing this!
Bob

**Comment by helgeerbe** [comment, marked as answer]
Hi @broswell ,

if you already running home assistant I would propose to create a simple automation.
Code could look like this:
````yaml
alias: remote next image
description: next image on picframe when pushing button on remote
mode: single
trigger:
  - platform: mqtt
    topic: rtl_433/alarm/devices/Generic_Remote/57173/cmd 48
condition: []
action:
  - service: mqtt.publish
    data:
      topic: homeassistant/switch/picframe_next/set
      payload: 'ON'
````

If you don't use home assistant. I would recommend your option 2.

I wouldn't modify picframe's code. You will have to patch it on every update.
