### DISCUSSION TITLE
MQTT: sensor.picframe_image_date missing?

### DISCUSSION THREAD

**Discussion by clintiepoo** [helgeerbe/picframe#223] [Q&A] [answered]
I set up MQTT and home assistant. Everything works ok, but I'm not seeing the picframe_image_date sensor. Is this a bug, or how can I enable this sensor?

![image](https://user-images.githubusercontent.com/33547246/149442994-63e83c8f-4c96-4acf-82b9-f6b63a5047cb.png)

**Comment by helgeerbe** [comment]
I guess you forgot to edit your configuration.yaml file https://github.com/helgeerbe/picframe/wiki/Homeassistant#configurationyaml

**Reply by clintiepoo** [reply]
hi - I edited the config. Everything else works, just not the date sensor.

**Reply by helgeerbe** [reply]
have you restarted home_assistant?

**Reply by clintiepoo** [reply]
I did just now. Still this sensor isn’t showing up.

**Reply by clintiepoo** [reply]
Since this is MQTT, should I look in MQTT explorer for a certain entry? Just trying to track this down.

**Comment by helgeerbe** [comment, marked as answer]
Please check in developers tool for the entity id sensor.picframe_image. Does it has an attribute `Exif DateTimeOriginal`?
![Bildschirmfoto 2022-01-14 um 16 33 18](https://user-images.githubusercontent.com/59169507/149542375-9e361a30-adc2-47e8-ba65-0e539e6aa452.png)

This number is an linux timestamp.

In configuration.yaml you create a template sensor which creates a human readable time format.

In developer tools->template you can copy this in the template editor: `{{ state_attr('sensor.picframe_image', 'EXIF DateTimeOriginal') | int | timestamp_custom('%d. %b. %Y %H:%M') }}` 

Does it show the correct time?

**Reply by clintiepoo** [reply]
That works - I'll just have to make a sensor for this in the config.

**Reply by clintiepoo** [reply]
Here's what I did: 
```
sensor:
  - platform: template
    sensors:
      picframe_image_date:
        value_template: "{{ state_attr('sensor.picframe_image', 'EXIF DateTimeOriginal') | int | timestamp_custom('%b %d, %Y') }}"
        friendly_name: "Image Date"
```
