### DISCUSSION TITLE
Running Picframe on a pi4 with 7" touchscreen and HDMI

### DISCUSSION THREAD

**Discussion by COVID-19-CTI** [helgeerbe/picframe#280] [Q&A]
Greetings! 
I'm running picframe on a Rpi4 under Buster using the "official" 7" touchscreen connected by the GPIO connector. Runs like a champ. 

Now today I got ambitious and thought about using the 7" touchscreen to control picframe, and an HDMI monitor to display the pictures. 

I plugged a HDMI monitor into the first port, and it was recognized by the OS and mirrored the terminal at boot time ( My pi is set to boot to terminal then automatically start picframe as a service as per the wiki/instructions). 

When picframe started, it treated the 7" and the HDMI monitors as if they were one large monitor. The pictures display half on the 7" the other half on the HDMI. 

Is there a way to force picframe to : 
- Only use the HDMI, leaving the 7" to be a terminal ? 
- Only use the HDMI for pictures, leaving the 7" blank but still in the window manager, so I can open a web browser and control picframe ( http port 9000 ) ? 
- Some other idea that I had not thought of but allows this? 

The upshoot is to use the 7" touchscreen to control picframe, and the HDMI to view pictures. 

Thanks!

**Comment by helgeerbe** [comment]
Hm,

I guess you have to start the window manager (desktop) to achieve what you want.

I would try to adjust configuration.yaml:

````yaml
  display_x: 0                            # offset from left of screen (can be negative)
  display_y: 0                            # offset from top of screen (can be negative)
  display_w: null                         # width of display surface (null->None will use max returned by hardware)
  display_h: null                         # height of display surface
````

I would start chrome over a script:

````ssh
chromium-browser --window-position=0,0 --window-size=800,600 http://picframe:9000
`````

Never tested it. I'm curious if this is working.
