### ISSUE TITLE
Directory listing in HomeAssistant drop-down menu is not alphabetized

### ISSUE THREAD

**Issue by jeffalperin** [helgeerbe/picframe#127]
The drop-down menu for ```input_select.picframe_directory``` appears to be in an arbitrary order rather than alphabetical.

I've not tried yet, be perhaps this could be addressed by adding ```|sort``` in the getter (`picframe_directory_get`) and/or setter (`picframe_directory_set`) automations for ```input_select.picframe_directory```?

**Comment by helgeerbe** [comment]
Hi Jeff,

sorry for the delayed answer. Currently picframe just reads the folder structure and doesn't do any kind of sorting. So I guess to do the sort in in the home assistant template would be fine. Have you done it already and can you provide the code snippet? Otherwise I could do it.

**Comment by jeffalperin** [comment]
Hi, Helge.  I have not done it.  (I started playing with it, but got distracted with another project.)  Thanks for taking a look!

**Comment by helgeerbe** [comment]
Hi Jeff,

try this in ``picframe_directory_get`` automation

````yaml
service: input_select.set_options
data:
  options: '{{ state_attr(''sensor.picframe_directory'', ''directories'') | sort }}'
entity_id: input_select.picframe_directory
````

Is this working for you?
