### ISSUE TITLE
Issue with Home Assistant integration

### ISSUE THREAD

**Issue by jeffalperin** [helgeerbe/picframe#78]
Following the instructions in the wiki, I'm mostly successful in integrating picframe with Home Assistant, but am seeing some errors (even though picframe appears to be functioning correctly):

 After initiating picframe from the command line with this command:
`export DISPLAY=:0 && /usr/bin/python3 /home/pi/picframe_data/run_start.py /home/pi/picframe_data/config/configuration.yaml`
I get errors in the console which look like this:
`192.168.7.48 - - [19/Mar/2021 13:07:02] code 400, message Bad request version ('\x10Y9\x90ÜÓ\x06\x07ï¡2âx}')
192.168.7.48 - - [19/Mar/2021 13:07:02] code 400, message Bad request version ('£ÌbQÉ}¦\x0e;_\\Ár\x89ºÅHºJR*\x03\x01©\x16')
192.168.7.48 - - [19/Mar/2021 13:07:02] code 400, message Bad request version ('ç\x81\x00$\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')`
(The .48 IP address is for the Windows desktop PC which is accessing Home Assistant via browser.)

Any ideas of what to look at to resolve this?

EDIT:
Just confirmed that this problem occurs only when `use_http: True` in configuration.yaml.

**Comment by helgeerbe** [comment]
Hm, looks for me the url encoding in home assistant is not working probably. 

Do you see the image in home assistant?

Under developer tools, there is a template editor in home assistant. When you paste `![Image](http://192.168.7.48:9000/{{ states('sensor.picframe_image') | urlencode }})` What do you  get for an url? Can you copy this url to your browser. Does the image show up?

One other thing. Check if you are using ssl. If you are using ssl you have to use `https`  otherwise 'http'

**Comment by jeffalperin** [comment]
I do **not** see the image in Home Assistant.  (I was going to inquire about that.)  Also, I am **not** using SSL.  

When I paste the template code into the template editor, the resulting URL `![Image](http://192.168.7.48:9000/Canadian%20Rockies_DSC_0614_3840x2160.jpg)` does **not** work, but that's because 192.168.7.**48** is the IP of my Windows desktop where I'm running HA in a browser.  The rPi4 running `picframe` is at 192.168.7.**50**.  When I change the IP to .50, I **do** see the image in the browser.

So, where is the .48 IP coming from?  (The error messages being thrown use that IP, too.)

Thanks for your help!

**Comment by helgeerbe** [comment]
Ah OK, that makes sense. .48 is logged where the request comes from. So to sort it out for me.

1. mqtt is up and running, because you see the image name in home assistant.
2. In the markdown card you have set in the yaml code `http://192.168.7.50:9000`. The ip from your picframe
3. home assistant **does not use ssl** (`http://myhomeassistant:8123/lovelace`). If you set up home assistant to use ssl it will always use ssl to query the image. No matter if you use 'http' or 'https' in your image url.
4. ssl is off on picframe

Can you post your yaml code? Shoud look like this:

````YAML
cards:
  - type: markdown
    content: >-
      ![Image](http://192.168.7.50:9000/{{
      states('sensor.picframe_image') | urlencode }})
````

I deleted the rest in the card.

**Comment by jeffalperin** [comment]
Your 1 -4 are all correct.

I discovered the problem preventing the image from showing in Home Assistant:  I had http**s** instead of just http for the url in the yaml.  I've corrected that so the current yaml is:

```yaml
cards:
  - type: markdown
    content: >-
      {% if state_attr("sensor.picframe_image", "IPTC Object Name") -%}

      ## {{ state_attr("sensor.picframe_image", "IPTC Object Name") }}
       {%- else -%}
      ## {{ states("sensor.picframe_image") }}

      {%- endif %}

      {% if state_attr("sensor.picframe_image", "IPTC Caption/Abstract") -%}
         {{ state_attr("sensor.picframe_image", "IPTC Caption/Abstract") }}
      {% endif %}

      ![Image](http://192.168.7.50:9000/{{ states('sensor.picframe_image') |
      urlencode }})

      {% if state_attr("sensor.picframe_image", "location") != None %}
        {{ state_attr("sensor.picframe_image", "location") }}
      {%- else -%}
        No GPS Data.
      {%- endif %}
  - type: glance
    entities:
      - entity: switch.picframe_back
        tap_action:
          action: toggle
      - entity: switch.picframe_paused
        tap_action:
          action: toggle
      - entity: switch.picframe_next
        tap_action:
          action: toggle
      - entity: switch.picframe_shuffle
        tap_action:
          action: toggle
      - entity: switch.picframe_delete
        tap_action:
          action: toggle
    show_name: false
    show_state: false
    state_color: true
    show_icon: true
  - type: entities
    entities:
      - entity: sensor.picframe_image
        name: Filename
      - entity: sensor.picframe_image_date
        icon: 'mdi:calendar-clock'
        name: Date
      - type: attribute
        entity: sensor.picframe_image
        attribute: EXIF ExposureTime
        unit: sec
        icon: 'mdi:camera-timer'
        name: Shutter speed
      - type: attribute
        entity: sensor.picframe_image
        attribute: EXIF FNumber
        unit: f
        icon: 'mdi:camera-iris'
        name: Aperture
      - type: attribute
        entity: sensor.picframe_image
        attribute: EXIF ISOSpeedRatings
        icon: 'mdi:film'
        name: ISO
      - type: attribute
        entity: sensor.picframe_image
        attribute: EXIF FocalLength
        unit: iso
        icon: 'mdi:signal-distance-variant'
        name: Focal length
      - type: attribute
        entity: sensor.picframe_image
        attribute: Image Model
        unit: mm
        icon: 'mdi:camera'
        name: Camera
      - type: attribute
        entity: sensor.picframe_image
        attribute: IPTC Keywords
        icon: 'mdi:tag'
        name: Tags
  - aspect_ratio: '3:2'
    dark_mode: false
    default_zoom: 11
    entities:
      - entity: sensor.picframe_image
    type: map
    hours_to_show: 0
type: vertical-stack

```
I'm still getting errors like this, though:
`
192.168.7.48 - - [20/Mar/2021 12:58:10] code 400, message Bad request version ('3\x10\x00$\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
192.168.7.48 - - [20/Mar/2021 12:58:10] code 400, message Bad request version ('à\x17ßUÀ\x00$\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
192.168.7.48 - - [20/Mar/2021 12:59:17] code 400, message Bad request version ('\x16ùÊ\x00QõM¨Q¶VOÓ\x92=¹îh¬"6?\x91,\x8b0e\x7f\x00$\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
192.168.7.48 - - [20/Mar/2021 12:59:17] code 400, message Bad request version ('\x9dµ\x07\x01\x12È\x7f±¾ØÁßßgm\x86Ë}èås±¨Ùñ*o\x12°\x91\x00$\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
`
